# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: preonic_rev3

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

  steps:
      - name: Generate artifact name
        id: generate-name
        run: |
          echo "::set-output name=artifact::${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.generate-name.outputs.artifact }}
          path: ./